### ISSUE TITLE
Error in confirmation after grademe - Exam Rank 02

### ISSUE THREAD

**Issue by lbordonal** [JCluzet/42_EXAM#38] opened 2022-12-23 10:54 UTC
Hi, it's not a big issue at all, but...

When the program ask me to confirm the grademe operation with <code>[y/N]</code> , he don't receive <code> y </code> as a parameter, only <code> Y </code>. If I go to settings and enable the cheat commands, the program accepts only the correct parameter <code> y </code> to confirm grademe.

I looked in the code of <code> grade_request.cpp </code> and it seems correct ( <code> if (input == "y" || input == "Y") </code>), but for any reason the program only accept <code>Y</code> (without enable cheat commands) or <code>y</code>(cheat commands enabled).

**Comment by JCluzet** [comment] 2022-12-27 01:29
Hi @ibordonal 👋

First of all, thank you for using 42_EXAM.
Any issue deserves to be fixed to make the program reliable for everyone :)

But this problem is quite strange...
I can't reproduce it on my side
Could you tell me what OS you are on and its version?

**Comment by lbordonal** [comment] 2022-12-27 01:44
Hi @JCluzet!

For now, as I am out of 42 until Wednesday, and I found this issue there, I can only tell you that is a Ubuntu OS.
In Wednesday I'll check it out and I update the issue with the exactly version of OS.

**Comment by lbordonal** [comment] 2022-12-28 10:05
Hi @JCluzet !

We are using Ubuntu 20.04.2 LTS.

**Comment by JCluzet** [comment] 2023-01-11 23:26
Hi @lbordonal 👋
Sorry for the delay,
I tried to reproduce the Issue at school and at home with Ubuntu 22.04.

Everything works fine on my side and I don't encounter this error.
If you have more information you can reopen this Issue, for now I close it.

**Closed by JCluzet** 2023-01-11 23:26 UTC
