### ISSUE TITLE
Can’t use 42_MAKE & 42_EXAM with Kali

### ISSUE THREAD

**Issue by cuhlig42** [JCluzet/42_EXAM#44] opened 2023-01-11 08:36 UTC
### Discussed in https://github.com/JCluzet/42_EXAM/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **cuhlig42** January 10, 2023</sup>
ill add more detail today :)

**Comment by cuhlig42** [comment] 2023-01-11 17:42
So I hope the video work this time and that Im now in the right section. :)
Sorry for the trouble that I made.
https://drive.google.com/file/d/1W4JbILeiaiuyOz-9KTY24KwwIHXyjUDU/view?usp=sharing

**Comment by JCluzet** [comment] 2023-01-11 18:06
Thank you for your video. 

42_MAKE is a program to automatically create a Makefile based on a project. 

It will automatically look at where you run the command Grademe.fr and look at the project that is in it. 
You run the command on your desktop, it's a mistake because the program will look at ALL the .c and .cpp files that are in ALL the folders on your desktop. 

You have to run the command Grademe IN your project. 
For example if you want to create a Makefile for your project Get_Next_Line you have to run the command in your repo (folder) get_next_line and not on your Desktop. 

I will add a warning if someone runs it from the Desktop. 

Concerning 42_EXAM indeed it is not normal. 
I'll try to fix it tonight.

**Comment by cuhlig42** [comment] 2023-01-11 20:15
ty for your answer 

"42_MAKE is a program to automatically create a Makefile based on a project."

ahh ok good to know ty I first thought I have to create a make file to do the test Exams. 

"You have to run the command Grademe IN your project.
For example if you want to create a Makefile for your project Get_Next_Line you have to run the command in your repo (folder) get_next_line and not on your Desktop."

ty for the info

ok then i will wait :)

**Comment by JCluzet** [comment] 2023-01-11 23:12
Hi 
I have just now solved the problem.
Normally you can now run 42_EXAM without any problem, keep me informed.

Concerning 42_MAKE I added a Warning which explains how to use it.

**Comment by JCluzet** [comment] 2023-01-14 22:00
I close the Issue because I think the problem is solved, if you still have a problem you can open it again.

**Closed by JCluzet** 2023-01-14 22:00 UTC
Labels: bug
